# -*- coding: utf-8 -*-
"""Bucles(LoopsPython).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p770dMURyE4juda1ehPoPXGOfitQd-cP
"""

for i in range(2,101,2):
  print("Cuenta actual: ", i)

edad = int(input("Digite su edad: "))
for n in range(1, edad + 1):
  print("Años cumplidos: ", n)

num = int(input("Digite un número entero positivo: "))
for i in range(1, num + 1, 2):
  print("Números impares: ", i, ",")

acu = 0

for i in range(0,101,2):
  acu = acu + i
print(f"El total de la suma de los números pares del 1 al 100 es = {acu}")