# -*- coding: utf-8 -*-
"""Taller de RefuerzobyCesar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qVO3M6WexOYlKwt-lYFiInpj8yTR4eEC

Un vendedor recibe un sueldo base más un 10% extra por
comisión de sus ventas, el vendedor desea saber cuánto
dinero obtendrá por concepto de comisiones por las tres
ventas que realiza en el mes y el total que recibirá en
el mes tomando en cuenta su sueldo base y comisiones.
"""

# Este código permite calcular las comisiones del 10% generadas por 3 ventas y refleja el total a recibir a final de mes
sueldoBase = float(input("Digite su salario básico "))
print(f"Sueldo Base: ${sueldoBase:,.0f}")
venta1 = float(input("\nDigite el valor de la primera venta: "))
venta2 = float(input("\nDigite el valor de la segunda venta: "))
venta3 = float(input("\nDigite el valor de la tercera venta: "))
comisionv1 = venta1 * 0.10  
comisionv2 = venta2 * 0.10
comisionv3 = venta3 * 0.10
totalcom = comisionv1 + comisionv2 + comisionv3
print(f"\nValor total adquirido por comisiones = ${totalcom:,.0f} \nValor total a recibir a final de mes = ${sueldoBase + totalcom:,.0f}")

"""Una tienda ofrece un descuento del 15% sobre el total
de la compra y un cliente desea saber cuánto deberá
pagar finalmente por su compra.
"""

# El código permite calcular el descuento del 15% del total de la compra
totalcompra = float(input("Digite el valor total de la compra realizada "))
print(f"Valor total de la compra: ${totalcompra:,.0f}")
valordescuento = totalcompra * 0.15
valorcondes = totalcompra - valordescuento
print(f"Valor total de la compra con descuento del 15%= ${valorcondes:,.0f}")

"""Un alumno desea saber cuál será su calificación final en
la materia de Algoritmos. Dicha calificación se compone
de tres exámenes parciales.
"""

# El código permite calcular su calificación final de acuerdo a los resultados de sus tres parciales de cada corte
parcial1 = float(input("Digite la nota del primer parcial "))
parcial2 = float(input("Digite la nota del segundo parcial "))
parcial3 = float(input("Digite la nota del tercer parcial "))
notafinal = (parcial1 + parcial2 + parcial3)/3
print(f"Nota final Algoritmos: {notafinal}")

"""Un maestro desea saber qué porcentaje de hombres y que
porcentaje de mujeres hay en un grupo de estudiantes.
"""

# El código permite visualizar a manera porcentual el número de estudiantes agrupados con género
mujeres = int(input("Digité el número de mujeres en el grupo de estudiantes "))
hombres = int(input("Digité el número de hombres en el grupo de estudiantes "))
totalest = mujeres + hombres
pormuj = (mujeres * 100)/totalest
porhom = (hombres * 100)/totalest
print(f"Porcentaje mujeres = %{pormuj} \nPorcentaje hombres = %{porhom}")