# -*- coding: utf-8 -*-
"""Taller#1"Declaring variables".ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k_-ia6Meoeg3gd7MStVNoE3Fv7g9GiFE
"""

#El código permite a empleados actualizar su información y verificar los beneficios a los que pueden acceder
nIdentificacion = input("Digite su número de identificación ")
nombres = "Cesar David"
apellidos = input("Digite sus apellidos ")
direccion = input("Digite su dirección de residencia ")
telefono = 3202367839
edad = int(input("Digite su edad "))
estado_civil = input("Digite su estado civil ")
nhijos = int(input("¿Cuántos hijos tiene? "))
estaturacm = 180
fecha_contratacion = input("Digite la fecha de contratación en su empresa actual (Día/mes/año) ")
sueldo_basico = float(input("Digite aquí su sueldo basico "))
dias_laborados = int(input("Digite los días que ha laborado en su empresa actual "))
print("Número de identificación: ", nIdentificacion, "\n", "Nombres: ", nombres, "\n", "Apellidos: ", apellidos, "\n", "Dirección de residencia: ", direccion, "\n", "Teléfono: ", telefono, "\n", "Edad: ", edad, "\n", "Estado civil: ", estado_civil, "\n", "Número de hijos: ", nhijos, "\n", "Estatura: ", estaturacm, "\n", "Fecha de contratación (Día/mes/año): ", fecha_contratacion, "\n", "Sueldo básico: ", sueldo_basico, "\n", "Días laborados a la fecha: ", dias_laborados)
print("\n*********************************************************")
print("\nEL EMPLEADO ES ELEGIBLE A LOS SIGUIENTES BENEFICIOS: ")
if edad >= 55:
  bono = sueldo_basico * 0.05
  print(f"Bono de prepensión: ${bono:,.0f}")
if estado_civil == "Casado" and nhijos > 0:
  print("Paseo anual en diciembre")
if sueldo_basico >= 1000000 and sueldo_basico < 1500000:
  com2 = sueldo_basico * 0.2
  print(f"Comisión del 2%: {com2:,.0f}")
if sueldo_basico >= 1500001 and sueldo_basico < 2000000:
  com5 = sueldo_basico * 0.5
  print(f"Comisión del 5%: {com5:,.0f}")
if dias_laborados > 20 and sueldo_basico < 1000000:
  print("Bono de alimentación")

# Operadores matemáticos en Python
num1 = int(input("Digite el número 1: "))
num2 = int(input("Digite el número 2: "))
res = num1 + num2
#Print Opción 1 con format
#print("La suma es = {}".format(res))
#Print Opción 2 con format (Acortada)
print(f"La suma de {num1} y {num2} es = {res}")

"""CALCULADORA +-*/"""

num1 = int(input("Digite el número "))
num2 = int(input("Digite el número "))

suma = num1 + num2
resta = num1 - num2
multi = num1 * num2
divi = num1 / num2

print(f"\nEl resultado de la SUMA es= {suma}")

"""Se recibe una venta por concepto de un producto, se require aplicar el IVA (19%) y conocer el total a pagar con el IVA incluido"""

# variable que captura la venta y aplica el IVA automáticamente
venta = float(input("¿cuánto fue el total de la compra"))
iva = venta * 0.19
total = venta + iva
print(f"El Iva es = ${iva:,.0f} y el total a pagar es = ${total:,.0f}")

"""Se necesita un sistema que reciba tres calificaciones parciales de un alumno y en base a estas darle su promedio """

cal1 = float(input("Digite la calificación 1 "))
cal2 = float(input("Digite la calificación 2 "))
cal3 = float(input("Digite la calificación 3 "))

promedio = (cal1 + cal2 + cal3)/3

print(f"El promedio es= {promedio}")